on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    steps:
      - run: |
          echo "Maven Message: $MESSAGE"
        shell: bashs
        env:
          MESSAGE: ${{ inputs.message }}
