on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Maven Message: $MESSAGE ${date}" > file.txt
        shell: bash
        env:
          MESSAGE: ${{ inputs.message }}
