on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          date=date()
          echo "Maven Message: $MESSAGE $date" > ${GITHUB_WORKSPACE}/file.txt
        shell: bash
        env:
          MESSAGE: ${{ inputs.message }}
      - uses: actions/upload-artifact@master
        with:
          name: my-data
          path: ${GITHUB_WORKSPACE}/file.txt
