on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: my-data
          path: .
      - run: |
          ls -l
          cat file.txt
        shell: bash
        env:
          MESSAGE: ${{ inputs.message }}

